MOVE_DISTANCE = 20

BALL_SHAPE = "circle"
BALL_COLOUR = "purple"
BALL_INIT_POSITION = (0, 0)
BALL_BOUNCE = 280
BALL_MOVE_X = 10
BALL_MOVE_Y = 10
BALL_SPEED = "slowest"

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_COLOUR = "black"
SCREEN_TITLE = "Pong"
SCREEN_TRACER = 0

DIRECTION_UP = 90
DIRECTION_DOWN = 270

PADDLE_LEFT_INIT = (-350, 0)
PADDLE_RIGHT_INIT = (350, 0)
PADDLE_WID = 5
PADDLE_LEN = 1
PADDLE_X = 350
PADDLE_Y = 0
PADDLE_MOVE = 20
PADDLE_COLOUR = "white"
PADDLE_SHAPE = "square"
PADDLE_DISTANCE = 50
PADDLE_XCOR_DISTANCE = 320

SCOREBOARD_COLOUR = "white"
SCOREBOARD_POSITION = (0, 260)
SCOREBOARD_FONT = ("Courier", 80, "normal")
SCOREBOARD_ALIGN = "center"
