STARTING_POSITIONS = [(0, 0), (-20, 0), (-40, 0)]
MOVE_DISTANCE = 20

COLLISION_FOOD = 15
COLLISION_BORDER = 290
COLLISION_TAIL = 10

SNAKE_COLOUR = "white"
SNAKE_SHAPE = "square"

FOOD_SHAPE = "circle"
FOOD_COLOUR = "green"
FOOD_LEN = 0.5
FOOD_WIDTH = 0.5
FOOD_SPEED = "fastest"

DIRECTION_UP = 90
DIRECTION_DOWN = 270
DIRECTION_LEFT = 180
DIRECTION_RIGHT = 0

SCOREBOARD_COLOUR = "white"
SCOREBOARD_POSITION = (0, 260)
SCOREBOARD_FONT = ("Arial", 24, "normal")
SCOREBOARD_ALIGN = "center"
